services:
  db:
    image: mysql:8.4
    container_name: mysql_db
    command: mysqld --character-set-server=utf8mb4
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data-new:/var/lib/mysql


  app:
    build: .
    container_name: api_blackbelt
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

volumes:
  mysql-data-new:
